### ISSUE TITLE
Les perms ne doivent pas être gérées par User mais par (un futur) FileSystem

### ISSUE THREAD

**Issue by izanagi1995** [ES-Community/ES-OS#1]
Comme dit dans le titre
TODO : FileSystem

**Comment by izanagi1995** [comment]
Mea culpa, j'ai pas exploré les autres branches haha

**Comment by fraxken** [comment]
@izanagi1995 Le fileSystem est optionnelle (donc les permissions ne peuvent être aucunement lié). Il est donc plus logique de liée une permission à l'OS ou plus précisément à la session.

Même sur tout les systèmes "réel" les permissions sont belle est bien une entité du core.

**Comment by izanagi1995** [comment]
Les permissions dans le core? Peux-tu être un peu plus explicite? J'ai
toujours cru que les perms étaient liées au FS

**Comment by fraxken** [comment]
Les permissions sont liées à des ressources (C'est le plus souvent des fichiers ok, mais pas que). Puis il ne faut pas oublier le contexte du projet (Vous abordez la chose avec une logique qui est nécessaire à un OS réel, ce n'est pas notre cas). 

Il faut réfléchir la chose dans le sens d'un Middleware dans nôtre cas.
